# Generated by Django 3.0.7 on 2020-12-31 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('answer', models.TextField(max_length=2048)),
                ('correct', models.BooleanField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('expired', models.BooleanField(blank=True, default=False)),
                ('marked', models.BooleanField(blank=True, default=False)),
                ('reviewed', models.BooleanField(blank=True, default=False)),
                ('passed', models.BooleanField(blank=True, default=False)),
                ('archived', models.BooleanField(blank=True, default=False)),
                ('turned_in', models.DateTimeField(blank=True, default=None, null=True)),
                ('key', models.CharField(max_length=15)),
                ('points', models.IntegerField(default=0)),
                ('points_open_response', models.IntegerField(default=0)),
                ('marked_by', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('question', models.CharField(max_length=2048)),
                ('question_type', models.IntegerField()),
                ('category', models.IntegerField()),
                ('point_value', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_response', models.TextField(blank=True, max_length=2048)),
                ('correct', models.BooleanField(blank=True, default=True)),
                ('review', models.TextField(blank=True, max_length=2048)),
                ('open_response_points', models.IntegerField(blank=True, default=0)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Answer')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Question')),
            ],
        ),
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('exam_name', models.CharField(max_length=64)),
                ('questions_one', models.ManyToManyField(blank=True, related_name='rev_question_one', to='exam.Question')),
                ('questions_two', models.ManyToManyField(blank=True, related_name='rev_question_two', to='exam.Question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExamTemplate'),
        ),
        migrations.AddField(
            model_name='exam',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Question'),
        ),
    ]
